name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.1
  - pip
  - scikit-learn=1.6.1
  - seaborn=0.13.2
  - pip:
      - pytest 
      - mlflow==2.8.0
      - cloudpickle==3.1.1