name: ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*
  - pip
  - scikit-learn=1.6.1
  - seaborn=0.13.*
  - pip:
      - mlflow==2.8.0
      - cloudpickle==2.2.1  # Changed to version compatible with mlflow
      - pytest