name: ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.*  # More flexible version specification
  - pip
  - scikit-learn=1.3.*  # Allowing patch version updates
  - seaborn=0.13.*  # Allowing patch version updates
  - pip:
      - mlflow==2.8.0
      - cloudpickle==3.1.1
      - pytest
