name: ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - scikit-learn=1.3.2
  - seaborn=0.13.2
  - pip:
      - mlflow==2.8.0
      - cloudpickle==3.1.1
      - pytest
