name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # ✅ Lebih aman dan stabil
  - pip
  - scikit-learn=1.3.2  # ✅ Kompatibel dengan mlflow 2.8.0
  - seaborn=0.13.2
  - pip:
      - pytest
      - mlflow==2.8.0
      - cloudpickle==3.1.1
